### ISSUE TITLE
Remove binaries from the repository

### ISSUE THREAD

**Issue by dadoonet** [vijayan007/data-copier#2]
IMHO it's better not to store any binary content as part of the source code, like jars you added in `run` dir.
We can easily within the Maven build a distribution zip file which contains all the content of the run dir on demand (maven assembly plugin would help).

Then if you publish your project on Sonatype/Maven central, you'll be able to distribute it from there and also share the JAR file and the pom on maven. Which will made all that reusable by anyone.

**Comment by vijayan007** [comment]
Sorry for late response, yes I agree with you please remove and raise a pull request

**Comment by dadoonet** [comment]
I won't have time to work on that and I'm not using that code anyway.

**Comment by vijayan007** [comment]
Removed
